smartive-education/design-system-component-library-yeahyeahyeah

packages/shared-ui/components/typography/Heading.tsx, packages/shared-ui/interfaces/Types.ts
Hier würde es genügen einen Type anstatt einem Interface zu verwenden.
=> use type instead of interface

packages/shared-ui/components/IconLink.tsx, packages/shared-ui/components/User.tsx, packages/shared-ui/components/buttons/Button.tsx, packages/shared-ui/stories/User.stories.tsx
use callbacks and story actions in user component and dependent components
=> use callbacks where they are needed

packages/design-system-component-library-yeahyeahyeah/README.md, packages/design-system-component-library-yeahyeahyeah/package.json, packages/design-system-component-library-yeahyeahyeah/styles/tailwind.css
=> feat(npm-package): use new npm package name, create readme

packages/design-system-component-library-yeahyeahyeah/components/buttons/Button.tsx, packages/design-system-component-library-yeahyeahyeah/components/icons/IconMap.tsx, packages/design-system-component-library-yeahyeahyeah/stories/buttons/Button.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/buttons/IconButton.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/buttons/NaviButton.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/icons/Icon.stories.tsx
=> fix(Button): #58 

packages/design-system-component-library-yeahyeahyeah/.storybook/preview.js, packages/design-system-component-library-yeahyeahyeah/components/IconLink.tsx, packages/design-system-component-library-yeahyeahyeah/stories/IconLink.stories.tsx
=> fix(IconLink): #57 - fix story, type in component ist now required

packages/design-system-component-library-yeahyeahyeah/components/User.tsx, packages/design-system-component-library-yeahyeahyeah/components/forms/WriteComponent.tsx, packages/design-system-component-library-yeahyeahyeah/components/mumble/Mumble.tsx, packages/design-system-component-library-yeahyeahyeah/components/typography/Heading.tsx
=> fix: #53 #54

packages/design-system-component-library-yeahyeahyeah/components/Spacing.tsx, packages/design-system-component-library-yeahyeahyeah/components/forms/WriteComponent.tsx, packages/design-system-component-library-yeahyeahyeah/components/mumble/Mumble.tsx, packages/design-system-component-library-yeahyeahyeah/components/typography/Heading.tsx, packages/design-system-component-library-yeahyeahyeah/components/typography/Paragraph.tsx, packages/design-system-component-library-yeahyeahyeah/stories/forms/WriteComponent.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/mumble/Mumble.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/typography/Heading.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/typography/Paragraph.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/typography/Typography.stories.tsx, packages/design-system-component-library-yeahyeahyeah/types/types.ts, tailwind.config.js
- Type TSpacing umbenannt auf: TmbSpacing
- In den Komponenten: prop "spacing" umbenannt auf "mbSpacing"
=> fix(spacing): rename spacing to mbSpacing #49

packages/design-system-component-library-yeahyeahyeah/components/Container.tsx, packages/design-system-component-library-yeahyeahyeah/components/mumble/Mumble.tsx, packages/design-system-component-library-yeahyeahyeah/stories/mumble/Mumble.stories.tsx
- removed background in container component for option "plain"
- added mbSpacing option for all mumbles
=> fix(Spacing): spacing options for mumble, cont. bg

packages/design-system-component-library-yeahyeahyeah/components/Avatar.tsx, packages/design-system-component-library-yeahyeahyeah/components/User.tsx, packages/design-system-component-library-yeahyeahyeah/components/forms/WriteComponent.tsx, packages/design-system-component-library-yeahyeahyeah/components/mumble/Mumble.tsx, packages/design-system-component-library-yeahyeahyeah/stories/forms/WriteComponent.stories.tsx
- Avatar positioning in write-component
- Avatar fixed with
- Update Write-Component API required props
- Update Write-Component responsive Header (User/Avatar)
=> fix(WriteComp/Avatar): resp. ava. req. props #51

packages/design-system-component-library-yeahyeahyeah/.storybook/main.js, packages/design-system-component-library-yeahyeahyeah/components/User.tsx, packages/design-system-component-library-yeahyeahyeah/components/buttons/README.md, packages/design-system-component-library-yeahyeahyeah/components/mumble/MumbleHeader.tsx, packages/design-system-component-library-yeahyeahyeah/env.d.ts, packages/design-system-component-library-yeahyeahyeah/package.json, packages/design-system-component-library-yeahyeahyeah/stories/buttons/Button.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/mumble/MumbleHeader.stories.tsx, yarn.lock
- Adding Button Readme.md example
- Added new storybook plugin "storybook-readme"
Needs: `yarn install`
=> Feature/documentation - Button README Example #62

packages/design-system-component-library-yeahyeahyeah/components/Avatar.tsx, packages/design-system-component-library-yeahyeahyeah/components/buttons/IconButton.tsx
- Resolve responsive Avatar and edit icon.
=> fix(MumbleHeader): responsive avatar

packages/design-system-component-library-yeahyeahyeah/docs/Container.md, packages/design-system-component-library-yeahyeahyeah/stories/Container.stories.tsx
=> feat:(Container): add/update readme

packages/design-system-component-library-yeahyeahyeah/.storybook/preview.js, packages/design-system-component-library-yeahyeahyeah/components/modal/Modal.tsx, packages/design-system-component-library-yeahyeahyeah/docs/Modal.md, packages/design-system-component-library-yeahyeahyeah/stories/modal/Modal.stories.tsx
- Include modal readme
- Set default values
- Preview: welcome first page
=> fix(Modal): include readme, preview order

packages/design-system-component-library-yeahyeahyeah/.storybook/main.js, packages/design-system-component-library-yeahyeahyeah/components/forms/InputForm.tsx, packages/design-system-component-library-yeahyeahyeah/package.json, packages/design-system-component-library-yeahyeahyeah/stories/forms/CheckBox.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/forms/InputForm.stories.tsx, yarn.lock
- installs new packages
- test on Form -> inputform
=> feat(InputForm): interaction test

packages/design-system-component-library-yeahyeahyeah/README.md, packages/design-system-component-library-yeahyeahyeah/components/Navigation.tsx, packages/design-system-component-library-yeahyeahyeah/stories/Navigation.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/forms/Switch.stories.tsx
fix: update npm package readme, fix related bugs in Navigation component
=> fix: update npm package readme

packages/design-system-component-library-yeahyeahyeah/components/ImageContainer.tsx, packages/design-system-component-library-yeahyeahyeah/components/mumble/MumbleHeader.tsx, packages/design-system-component-library-yeahyeahyeah/stories/ImageContainer.stories.tsx, packages/design-system-component-library-yeahyeahyeah/stories/mumble/Mumble.stories.tsx, packages/design-system-component-library-yeahyeahyeah/styles/ImageScale.tsx
- Should fix mobile view (center mumble-header in small mobile view)
=> fix(MumbleHeader): fix mobile view

packages/design-system-component-library-yeahyeahyeah/docs/MumbleHeader.md
- Updated "user" variant mode to static *xlarge*
=> fix(MumbleHeader): update readme

packages/design-system-component-library-yeahyeahyeah/components/IconLink.tsx, packages/design-system-component-library-yeahyeahyeah/components/ImageContainer.tsx, packages/design-system-component-library-yeahyeahyeah/components/branding/MumbleLogo.tsx, packages/design-system-component-library-yeahyeahyeah/components/buttons/InteractionButton.tsx, packages/design-system-component-library-yeahyeahyeah/components/buttons/ShareButton.tsx, packages/design-system-component-library-yeahyeahyeah/components/forms/FileUpload.tsx, packages/design-system-component-library-yeahyeahyeah/components/forms/InputForm.tsx
use boolean in conditions instead of strings - i had compiler issue earlier, this is why i used strings...
=> use boolean in conditions instead of strings

packages/design-system-component-library-yeahyeahyeah/stories/typography/Typography.stories.tsx
- All tabs "controls", "actions", "intercations" and "docs disabled
=> fix(Typography): disable tabs

packages/design-system-component-library-yeahyeahyeah/components/image/ImageContainer.tsx
- Fixing overflow hidden bug in iOS
=> fix(ImageContainer): overflow bug iOS

packages/design-system-component-library-yeahyeahyeah/components/form/InputForm.tsx, packages/design-system-component-library-yeahyeahyeah/stories/form/InputForm.stories.tsx
- Attribute "name" for input and textarea
=> fix(input, textarea): add missing attribute name

packages/design-system-component-library-yeahyeahyeah/components/button/NaviButton.tsx
Musste selbst mergen, da ich weitermachen musste.
=> fix: NaviButton

packages/design-system-component-library-yeahyeahyeah/components/form/UploadForm.tsx, packages/design-system-component-library-yeahyeahyeah/components/modal/Modal.tsx, packages/design-system-component-library-yeahyeahyeah/stories/modal/Modal.stories.tsx
=> feat(Modal): add third modal width

packages/design-system-component-library-yeahyeahyeah/components/image/MumbleLogo.tsx
=> fix(MumbleLogo): animate mumble
